
import { CoffeeItem, Promotion } from './types';

export const MENU_ITEMS: CoffeeItem[] = [
  {
    id: 1,
    name: 'Caramel Priline Machiatto',
    description: 'Espresso dengan karamel priline yang manis dan creamy.',
    details: 'Perpaduan sempurna espresso premium dengan sirup caramel priline dan susu yang lembut.',
    price: 25000,
    imageUrl: '/asset/Caramel Priline Machiatto.PNG',
    category: 'best-seller',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 2,
    name: 'Korean Manggo Milk',
    description: 'Susu mangga ala Korea yang segar dan manis.',
    details: 'Minuman susu dengan rasa mangga segar khas Korea, cocok untuk cuaca panas.',
    price: 22000,
    imageUrl: '/asset/Korean Manggo milk.PNG',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 3,
    name: 'Korean Blue Berry',
    description: 'Minuman blueberry ala Korea yang menyegarkan.',
    details: 'Rasa blueberry asam manis yang dipadukan dengan susu segar.',
    price: 22000,
    imageUrl: '/asset/Korean blue berry.PNG',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 4,
    name: 'Lemon Tea',
    description: 'Teh lemon segar yang menyegarkan.',
    details: 'Perpaduan teh premium dengan perasan lemon segar, cocok disajikan dingin.',
    price: 15000,
    imageUrl: '/asset/Lemon tea .PNG',
    category: 'standard',
    type: 'beverage',
    stock: 100,
  },
  {
    id: 5,
    name: 'Lychee Tea',
    description: 'Teh leci dengan aroma yang harum.',
    details: 'Teh dengan rasa leci yang manis dan harum, sangat menyegarkan.',
    price: 18000,
    imageUrl: '/asset/Lychee tea.PNG',
    category: 'standard',
    type: 'beverage',
    stock: 100,
  },
  {
    id: 6,
    name: 'Take Away Coffee Bottle',
    description: 'Kopi botol praktis untuk dibawa pergi.',
    details: 'Kopi susu premium dalam kemasan botol, cocok untuk menemani aktivitasmu.',
    price: 35000,
    imageUrl: '/asset/Take away coffe bottle.PNG',
    category: 'best-seller',
    type: 'beverage',
    stock: 30,
  },
  {
    id: 7,
    name: 'Vanilla Latte',
    description: 'Latte dengan aroma vanilla yang lembut.',
    details: 'Espresso premium dicampur susu dan sirup vanilla yang manis lembut.',
    price: 23000,
    imageUrl: '/asset/Vanill late.PNG',
    category: 'best-seller',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 8,
    name: 'Caramelized Latte',
    description: 'Latte dengan sentuhan karamel yang gurih manis.',
    details: 'Perpaduan espresso, susu, dan karamel yang dibakar untuk rasa yang kaya.',
    price: 24000,
    imageUrl: '/asset/caramelized latte.PNG',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 9,
    name: 'Green Tea',
    description: 'Green tea klasik yang menyegarkan.',
    details: 'Teh hijau premium dengan rasa yang khas dan menyegarkan.',
    price: 18000,
    imageUrl: '/asset/green tea.PNG',
    category: 'standard',
    type: 'beverage',
    stock: 100,
  },
  {
    id: 10,
    name: 'Hazelnut Latte',
    description: 'Latte dengan aroma hazelnut yang khas.',
    details: 'Espresso premium dengan susu dan sirup hazelnut yang gurih.',
    price: 24000,
    imageUrl: '/asset/hazenut latte.PNG',
    category: 'best-seller',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 11,
    name: 'Ice Kopi Aren',
    description: 'Kopi susu gula aren dingin yang menyegarkan.',
    details: 'Pilihan paling favorit bagi pecinta kopi susu dingin dengan gula aren.',
    price: 20000,
    imageUrl: '/asset/ice kopi aren.PNG',
    category: 'best-seller',
    type: 'beverage',
    stock: 100,
  },
];

export const PROMOTIONS_LIST: Promotion[] = [
  {
    id: 1,
    title: 'Korean Series',
    description: 'Nikmati kesegaran Korean Manggo Milk dan Korean Blue Berry hanya Rp 22.000!',
    imageUrl: '/asset/Korean Manggo milk.PNG',
  },
  {
    id: 2,
    title: 'Coffee Lovers',
    description: 'Caramel Priline Machiatto, Hazelnut Latte, dan Vanilla Latte favorit pelanggan!',
    imageUrl: '/asset/Caramel Priline Machiatto.PNG',
  }
];
