
import { CoffeeItem, Promotion } from './types';

export const MENU_ITEMS: CoffeeItem[] = [
  {
    id: 101,
    name: 'Butter Cream Sea Salt Latte',
    description: 'Koleksi terbaru Butter Cream dengan sentuhan rasa Sea Salt.',
    details: 'Bagian dari Butter Cream Collection. Tekstur foam yang tebal, gurih, dan creamy di atas espresso premium.',
    price: 28000,
    imageUrl: 'https://images.unsplash.com/photo-1594631252845-29fc458631b6?q=80&w=1200&auto=format&fit=crop',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 102,
    name: 'Caramel Priline Machiatto',
    description: 'Koleksi terbaru Butter Cream dengan rasa Caramel Priline.',
    details: 'Manisnya caramel priline berpadu dengan kelembutan butter cream di setiap sesapan.',
    price: 28000,
    imageUrl: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?q=80&w=1200&auto=format&fit=crop',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 103,
    name: 'Es Teler Azzahra',
    description: 'Menu baru Es Teler spesial dengan porsi melimpah.',
    details: 'Campuran alpukat, nangka, kelapa muda, dan mutiara dalam kuah susu rahasia Azzahra yang segar.',
    price: 25000,
    imageUrl: 'https://images.unsplash.com/photo-1473093226795-af9932fe5855?q=80&w=1200&auto=format&fit=crop',
    category: 'new',
    type: 'beverage',
    stock: 50,
  },
  {
    id: 1,
    name: 'Kopi Hitam',
    description: 'Kopi hitam murni khas Azzahra.',
    details: 'Biji kopi pilihan yang diseduh dengan teknik tradisional untuk aroma yang kuat.',
    price: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop',
    category: 'standard',
    type: 'beverage',
    stock: 100,
  },
  {
    id: 7,
    name: 'Ice Kopi Aren',
    description: 'Kopi susu gula aren dingin yang menyegarkan.',
    details: 'Pilihan paling favorit bagi pecinta kopi susu dingin dengan gula aren.',
    price: 20000,
    imageUrl: 'https://images.unsplash.com/photo-1551046710-444df46f7396?q=80&w=1200&auto=format&fit=crop',
    category: 'best-seller',
    type: 'beverage',
    stock: 100,
  },
  {
    id: 50,
    name: 'Sop Saudara',
    description: 'Spesialis Sop Saudara khas Azzahra.',
    details: 'Potongan daging sapi empuk dengan kuah rempah yang kaya rasa. Favorit sepanjang masa.',
    price: 12000,
    imageUrl: 'https://images.unsplash.com/photo-1547928576-a4a33237ecd3?q=80&w=1200&auto=format&fit=crop',
    category: 'best-seller',
    type: 'food',
    stock: 30,
  },
  {
    id: 61,
    name: 'Pisang Goreng Palm Sugar',
    description: 'Pisang goreng renyah dengan taburan gula palem.',
    details: 'Kombinasi manis dari palm sugar dan susu kental manis di atas pisang hangat.',
    price: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?q=80&w=1200&auto=format&fit=crop',
    category: 'best-seller',
    type: 'food',
    stock: 40,
  },
  {
    id: 64,
    name: 'Pisang Peppe',
    description: 'Pisang peppe tradisional khas yang dipukul tipis.',
    details: 'Sajian unik pisang tipis renyah dengan sambal pedas.',
    price: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?q=80&w=1200&auto=format&fit=crop',
    category: 'best-seller',
    type: 'food',
    stock: 40,
  },
  {
    id: 201,
    name: 'Nasi Kuning Azzahra',
    description: 'Nasi kuning harum dengan lauk lengkap.',
    details: 'Nasi yang dimasak dengan santan dan kunyit, disajikan dengan telur, serundeng, dan sambal.',
    price: 18000,
    imageUrl: 'https://images.unsplash.com/photo-1512058560366-cd2429598632?q=80&w=1200&auto=format&fit=crop',
    category: 'new',
    type: 'food',
    stock: 20,
  }
];

export const PROMOTIONS_LIST: Promotion[] = [
    {
        id: 1,
        title: 'Butter Cream Series',
        description: 'Nikmati kemewahan Butter Cream Collection terbaru kami (Sea Salt & Caramel) hanya Rp 28.000.',
        imageUrl: 'https://images.unsplash.com/photo-1594631252845-29fc458631b6?q=80&w=1200&auto=format&fit=crop',
    },
    {
        id: 2,
        title: 'Segarnya Es Teler',
        description: 'Es Teler Azzahra yang melimpah buahnya, segar kuahnya. Porsi besar hanya Rp 25.000!',
        imageUrl: 'https://images.unsplash.com/photo-1473093226795-af9932fe5855?q=80&w=1200&auto=format&fit=crop',
    }
];
